CREATE TABLE InvoiceDetail (
  RecID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
  InvoiceRecID varchar(100) DEFAULT NULL,
  UPC varchar(100) DEFAULT NULL,
  Quantity int DEFAULT NULL,
  TotalUnitAmount int DEFAULT NULL,
  TotalDiscountAmount int DEFAULT NULL,
  TotalSubTotal int DEFAULT NULL,
  TotalVATAmount int DEFAULT NULL,
  GrandTotal int DEFAULT NULL,
  StatisRecID int DEFAULT NULL,
  Cash varchar(100) NOT NULL,
  CardPayment varchar(100) NOT NULL
)


CREATE TABLE Invoice (
  RecID int NOT NULL  IDENTITY(1,1) PRIMARY KEY,
  CustomerRecID varchar(100) DEFAULT NULL,
  InvoiceNumber varchar(100) DEFAULT NULL,
  InvoiceDate varchar(100) DEFAULT NULL,
  BillingAddressRecID varchar(100) DEFAULT NULL,
  InvoiceDate1 varchar(20) DEFAULT NULL,
  PaymentTermRecID varchar(100) DEFAULT NULL,
  PaymentMethodRecID varchar(100) DEFAULT NULL,
  SalesPerson varchar(100) DEFAULT NULL,
  TotalUnitAmount varchar(100) DEFAULT NULL,
  TotalDiscountAmount varchar(100) DEFAULT NULL,
  TotalSubTotal varchar(100) DEFAULT NULL,
  TotalVATAmount varchar(100) DEFAULT NULL,
  GrandTotal varchar(100) DEFAULT NULL,
  CustomerNote varchar(100) DEFAULT NULL,
  EmployeeNote varchar(100) DEFAULT NULL,
  StatusRecID varchar(100) DEFAULT NULL,
  CreatedBranchRecID varchar(100) DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  ModifiedDate varchar(100) DEFAULT NULL,
  ModifiedTime varchar(100) DEFAULT NULL,
  InvoiceCreatedBy varchar(100) DEFAULT NULL,
  InvoiceCreatedDate varchar(100) DEFAULT NULL,
  InvoiceCreatedTime varchar(100) DEFAULT NULL,
  InvoiceApprovedBy varchar(100) DEFAULT NULL,
  InvoiceApprovedDate varchar(100) DEFAULT NULL,
  CashAmount numeric(10, 2) DEFAULT 0,
  CardAmount numeric(10, 2) DEFAULT 0,
)